#k apply -f pod-emptyDir.yaml
###################################################
# se o pod restartar o volume continuara
# mas se o pod for deletado, o volume tambem sera
###################################################
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: "256Mi"
